name: Build

on:
  pull_request:
    branches:
      'main'
  push:
    branches:
      'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      #      - uses: Xotabu4/selenoid-github-action@v2
      - uses: browser-actions/setup-chrome@v1
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - run: ./gradlew clean test
